# Generated by Django 4.2.3 on 2023-10-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_alter_city_options_alter_citylocation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citylocation',
            old_name='country',
            new_name='city',
        ),
    ]
