# Generated by Django 4.2.3 on 2023-09-12 04:44

import account.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('updated_at', django_jalali.db.models.jDateField(auto_now=True)),
                ('avatar', models.FileField(blank=True, upload_to='account/user/avatar', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'Active'), (2, 'Reported'), (3, 'Banned')], default=0)),
                ('activation_state', models.IntegerField(choices=[(0, 'White'), (1, 'Silver'), (2, 'Gold')], default=0)),
                ('user_name', models.CharField(max_length=33)),
                ('phone', models.CharField(max_length=17, unique=True, validators=[account.models.phone_validator])),
                ('is_staff', models.BooleanField(default=False)),
                ('gender', models.BooleanField()),
                ('national_code', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('birth_day', django_jalali.db.models.jDateField()),
                ('ref_code', models.CharField(max_length=8)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.country')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.citylocation')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
