# Generated by Django 5.0 on 2025-03-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'کاربر'), (2, 'پزشک'), (3, 'فروشنده')], default=1),
        ),
    ]
