# Generated by Django 4.2.3 on 2024-08-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(1, 'مرد'), (0, 'زن')], default=1, verbose_name=' '),
        ),
    ]
