# Generated by Django 4.2.3 on 2024-12-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
