# Generated by Django 4.2.3 on 2024-12-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_email_is_verify_user_phone_is_verify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_is_verify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_is_verify',
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP for email verification'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time when email OTP was sent'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='OTP for phone verification'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_otp_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time when phone OTP was sent'),
        ),
    ]
