# Generated by Django 5.0 on 2025-05-20 12:00

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
            options={
                'verbose_name': 'شناسه صنف',
                'verbose_name_plural': 'شناسه های صنف',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, unique=True)),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحد ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.FileField(upload_to='product/image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])], verbose_name='تصاویر')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(blank=True, max_length=19, null=True, verbose_name='شناسه بازرگانی')),
                ('name', models.CharField(max_length=33, unique=True, verbose_name='نام کالا')),
                ('key_name', models.CharField(blank=True, max_length=158, null=True, verbose_name='کلمه ی کلیدی')),
                ('type', models.IntegerField(blank=True, choices=[(0, 'گیاه'), (1, 'عرق'), (2, 'روغن'), (3, 'افشوره'), (4, 'شربت'), (5, 'قرص'), (6, 'کپسول'), (7, 'سمق'), (8, 'گل'), (9, 'دانه'), (10, 'برگ'), (11, 'ساقه'), (12, 'ریشه'), (13, 'پوست'), (14, 'میوه'), (15, 'پماد'), (16, 'ضماد'), (17, 'پودر'), (18, 'هسته'), (19, 'کرم'), (20, 'مکمل'), (21, 'شوینده'), (22, 'بخور'), (23, 'دود کردنی')], default=0, verbose_name='نوع کالا')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='معرفی محصول')),
                ('views', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('state', models.IntegerField(blank=True, choices=[(0, 'معلق'), (1, 'فعال'), (2, 'غیر فعال')], default=0, verbose_name='وضعیت کالا')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال بودن')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='کتگوری')),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.classid', verbose_name='شناسه صنف')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productunit', verbose_name='شناسه واحد')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product/image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])], verbose_name='تصاویر')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس محصول',
            },
        ),
    ]
