# Generated by Django 4.2.3 on 2023-10-19 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
            options={
                'verbose_name': 'شناسه صنف',
                'verbose_name_plural': 'شناسه های صنف',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=19)),
                ('name', models.CharField(max_length=33, verbose_name='نام کالا')),
                ('type', models.IntegerField(choices=[(0, 'Giah'), (1, 'Aragh'), (2, 'Roghan'), (3, 'Afshore'), (4, 'Sharbat'), (5, 'Ghors'), (6, 'Kapsol'), (7, 'Samgh'), (8, 'Gol'), (9, 'Dane'), (10, 'Barg'), (11, 'Saghe'), (12, 'Rishe'), (13, 'Post'), (14, 'Mive'), (15, 'Pomad'), (16, 'Zomad'), (17, 'Podr'), (18, 'Haste'), (19, 'Kerm'), (20, 'Mokamel'), (21, 'Shoyande'), (22, 'Bokhori'), (23, 'Dod Kardani')], verbose_name='نوع کالا')),
                ('material', models.IntegerField(choices=[(1, 'Baste Bandi'), (2, 'Pack'), (3, 'Dane E'), (4, 'Kiloe'), (5, 'Shishe E')], verbose_name='جنس کالا')),
                ('description', models.TextField()),
                ('price', models.IntegerField(verbose_name='واحد قیمت بر حسب کیلو')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'Active'), (2, 'De Active')], default=0, verbose_name='وضعیت کالا')),
                ('is_active', models.BooleanField(default=False)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.classid')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
            options={
                'verbose_name': 'شناسه صنف',
                'verbose_name_plural': 'شناسه های صنف',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product/image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])], verbose_name='تصاویر')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productunit'),
        ),
    ]
