# Generated by Django 4.2.3 on 2024-01-17 08:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.FileField(upload_to='product/image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])], verbose_name='تصاویر')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ClassId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22)),
            ],
            options={
                'verbose_name': 'شناسه صنف',
                'verbose_name_plural': 'شناسه های صنف',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(max_length=19, verbose_name='شناسه بازرگانی')),
                ('name', models.CharField(max_length=33, unique=True, verbose_name='نام کالا')),
                ('type', models.IntegerField(choices=[(0, 'گیاه'), (1, 'عرق'), (2, 'روغن'), (3, 'افشوره'), (4, 'شربت'), (5, 'قرص'), (6, 'کپسول'), (7, 'سمق'), (8, 'گل'), (9, 'دانه'), (10, 'برگ'), (11, 'ساقه'), (12, 'ریشه'), (13, 'پوست'), (14, 'میوه'), (15, 'پماد'), (16, 'ضماد'), (17, 'پودر'), (18, 'هسته'), (19, 'کرم'), (20, 'مکمل'), (21, 'شوینده'), (22, 'بخور'), (23, 'دود کردنی')], verbose_name='نوع کالا')),
                ('material', models.IntegerField(choices=[(1, 'بسته بندی'), (2, 'پک'), (3, 'دانه ای'), (4, 'کیلوای'), (5, 'شیشه ای')], verbose_name='جنس کالا')),
                ('description', models.TextField(verbose_name='جنس کالا')),
                ('price', models.IntegerField(verbose_name='واحد قیمت بر حسب واحد')),
                ('state', models.IntegerField(choices=[(0, 'معلق'), (1, 'فعال'), (2, 'غیر فعا')], default=0, verbose_name='وضعیت کالا')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال بودن')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.category', verbose_name='کتگوری')),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.classid', verbose_name='شناسه صنف')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, unique=True)),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحد ها',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='product/image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])], verbose_name='تصاویر')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'عکس محصول',
                'verbose_name_plural': 'عکس محصول',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productunit', verbose_name='شناسه واحد'),
        ),
    ]
