# Generated by Django 5.0 on 2025-04-24 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='key_name',
            field=models.CharField(blank=True, max_length=158, null=True, verbose_name='کلمه ی کلیدی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.classid', verbose_name='شناسه صنف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'معلق'), (1, 'فعال'), (2, 'غیر فعال')], default=0, verbose_name='وضعیت کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trade_id',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='شناسه بازرگانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, 'گیاه'), (1, 'عرق'), (2, 'روغن'), (3, 'افشوره'), (4, 'شربت'), (5, 'قرص'), (6, 'کپسول'), (7, 'سمق'), (8, 'گل'), (9, 'دانه'), (10, 'برگ'), (11, 'ساقه'), (12, 'ریشه'), (13, 'پوست'), (14, 'میوه'), (15, 'پماد'), (16, 'ضماد'), (17, 'پودر'), (18, 'هسته'), (19, 'کرم'), (20, 'مکمل'), (21, 'شوینده'), (22, 'بخور'), (23, 'دود کردنی')], default=0, verbose_name='نوع کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productunit', verbose_name='شناسه واحد'),
        ),
    ]
