# Generated by Django 4.2.3 on 2024-01-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='material',
        ),
    ]
