# Generated by Django 4.2.3 on 2023-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_class_id_alter_product_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=33, unique=True, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='productunit',
            name='name',
            field=models.CharField(max_length=22, unique=True),
        ),
    ]
