# Generated by Django 4.2.3 on 2024-01-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.IntegerField(choices=[(0, 'معلق'), (1, 'فعال'), (2, 'غیر فعال')], default=0, verbose_name='وضعیت کالا'),
        ),
    ]
