# Generated by Django 4.2 on 2024-01-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_name_alter_productunit_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'عکس محصول', 'verbose_name_plural': 'عکس محصول'},
        ),
        migrations.AlterModelOptions(
            name='productunit',
            options={'verbose_name': 'واحد', 'verbose_name_plural': 'واحد ها'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='جنس کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال بودن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='واحد قیمت بر حسب واحد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trade_id',
            field=models.CharField(max_length=19, verbose_name='شناسه بازرگانی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productunit', verbose_name='شناسه واحد'),
        ),
    ]
