# Generated by Django 4.2.3 on 2024-12-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='consumption_instruction',
        ),
    ]
