# Generated by Django 4.2 on 2024-01-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_category_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.IntegerField(choices=[(1, 'بسته بندی'), (2, 'پک'), (3, 'دانه ای'), (4, 'کیلوای'), (5, 'شیشه ای')], verbose_name='جنس کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.IntegerField(choices=[(0, 'معلق'), (1, 'فعال'), (2, 'غیر فعا')], default=0, verbose_name='وضعیت کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.IntegerField(choices=[(0, 'گیاه'), (1, 'عرق'), (2, 'روغن'), (3, 'افشوره'), (4, 'شربت'), (5, 'قرص'), (6, 'کپسول'), (7, 'سمق'), (8, 'گل'), (9, 'دانه'), (10, 'برگ'), (11, 'ساقه'), (12, 'ریشه'), (13, 'پوست'), (14, 'میوه'), (15, 'پماد'), (16, 'ضماد'), (17, 'پودر'), (18, 'هسته'), (19, 'کرم'), (20, 'مکمل'), (21, 'شوینده'), (22, 'بخور'), (23, 'دود کردنی')], verbose_name='نوع کالا'),
        ),
    ]
