# Generated by Django 5.0 on 2025-04-21 07:43

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivateLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ فعال\u200cسازی کاربر',
                'verbose_name_plural': 'لاگ\u200cهای فعال\u200cسازی کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserRefLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_referenced', to=settings.AUTH_USER_MODEL, verbose_name='معرفی شده توسط کاربر')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر جدید')),
            ],
            options={
                'verbose_name': 'لاگ معرفی کاربر',
                'verbose_name_plural': 'لاگ\u200cهای معرفی کاربران',
            },
        ),
    ]
