# Generated by Django 4.2.3 on 2023-10-20 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useractivatelogs',
            options={'verbose_name': 'لاگ فعال\u200cسازی کاربر', 'verbose_name_plural': 'لاگ\u200cهای فعال\u200cسازی کاربران'},
        ),
        migrations.AlterModelOptions(
            name='userreflogs',
            options={'verbose_name': 'لاگ معرفی کاربر', 'verbose_name_plural': 'لاگ\u200cهای معرفی کاربران'},
        ),
        migrations.AlterField(
            model_name='useractivatelogs',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='useractivatelogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='userreflogs',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='userreflogs',
            name='ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_referenced', to=settings.AUTH_USER_MODEL, verbose_name='معرفی شده توسط کاربر'),
        ),
        migrations.AlterField(
            model_name='userreflogs',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر جدید'),
        ),
    ]
