# Generated by Django 4.2.3 on 2024-01-17 08:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_visit', '0001_initial'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'تعلیق شده'), (1, 'تایید شده'), (2, 'ناموفق'), (3, 'گزارش شده')], default=0, verbose_name='وضعیت')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.salebasket', verbose_name='سبد خرید')),
            ],
            options={
                'verbose_name': 'بازخورد فروشگاه',
                'verbose_name_plural': 'بازخوردهای فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='FeedBackDoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'تعلیق شده'), (1, 'تایید شده'), (2, 'ناموفق'), (3, 'گزارش شده')], default=0, verbose_name='وضعیت')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_visit.doctorvisit', verbose_name='ویزیت')),
            ],
            options={
                'verbose_name': 'بازخورد ویزیت',
                'verbose_name_plural': 'بازخوردهای ویزیت ها',
            },
        ),
    ]
