# Generated by Django 5.0 on 2025-05-17 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'در انتظار'), (1, 'موفق'), (2, 'منقضی\u200cشده')], default=0, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='نامک')),
                ('is_feedback_sent', models.BooleanField(default=False, verbose_name='ارسال\u200cشده؟')),
            ],
            options={
                'verbose_name': 'سبد نظرسنجی',
                'verbose_name_plural': 'سبدهای نظرسنجی',
            },
        ),
        migrations.CreateModel(
            name='FeedbackObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده؟')),
            ],
            options={
                'verbose_name': 'نظر کاربر',
                'verbose_name_plural': 'نظرات کاربران',
            },
        ),
    ]
