# Generated by Django 5.0 on 2025-05-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
        ('sale', '0003_remove_salebasket_shop'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackcart',
            options={'verbose_name': 'سبد نظرسنجی', 'verbose_name_plural': 'سبدهای نظرسنجی'},
        ),
        migrations.AlterModelOptions(
            name='feedbackobject',
            options={'verbose_name': 'نظر کاربر', 'verbose_name_plural': 'نظرات کاربران'},
        ),
        migrations.AlterField(
            model_name='feedbackcart',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.salebasket', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='feedbackcart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='feedbackcart',
            name='is_feedback_sent',
            field=models.BooleanField(default=False, verbose_name='ارسال\u200cشده؟'),
        ),
        migrations.AlterField(
            model_name='feedbackcart',
            name='state',
            field=models.IntegerField(choices=[(0, 'در انتظار'), (1, 'موفق'), (2, 'منقضی\u200cشده')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='feedbackobject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='feedbackobject',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.feedbackcart', verbose_name='نظرسنجی'),
        ),
        migrations.AlterField(
            model_name='feedbackobject',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده؟'),
        ),
    ]
