# Generated by Django 4.2.3 on 2024-01-17 08:13

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEncyclopedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('created_at', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('author', models.CharField(max_length=100, unique=True, verbose_name='نویسنده')),
                ('abstract', ckeditor.fields.RichTextField()),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.FileField(upload_to='article-encyclopedia/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg', 'jpeg'])], verbose_name='تصویر')),
                ('registered', models.CharField(max_length=140, verbose_name='ثبت در')),
            ],
            options={
                'verbose_name': 'دانشنامه مقاله',
                'verbose_name_plural': 'دانشنامه مقالات',
            },
        ),
        migrations.CreateModel(
            name='ArticleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'مرجع',
                'verbose_name_plural': 'مراجع',
            },
        ),
        migrations.CreateModel(
            name='EncyclopaediaPrescriptionTherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'Report'), (2, 'Failed'), (3, 'Accept')], default=0)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('reason_for_consumption', models.TextField(verbose_name='علت مصرف')),
                ('prescription_compounds', models.TextField(unique=True, verbose_name='ترکیبات نسخه')),
                ('the_amount_of_compounds', models.TextField(verbose_name='میزان ترکیبات')),
                ('who_to_use', models.TextField(verbose_name='طریقه مصرف')),
                ('complications_of_compounds', models.TextField(verbose_name='عوارض ترکیبات')),
                ('prescription_complications', models.TextField(verbose_name='عوارض کلی نسخه')),
                ('version_reference', models.TextField(verbose_name='مرجع نسخه')),
            ],
            options={
                'verbose_name': 'دانشنامه نسخ درمانی',
                'verbose_name_plural': 'دانشنامه نسخ درمانی',
            },
        ),
        migrations.CreateModel(
            name='EncyclopediaCombinedDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'Report'), (2, 'Failed'), (3, 'Accept')], default=0)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='عنوان')),
                ('classification', models.CharField(max_length=100, verbose_name='طبقه بندی')),
                ('latin_name', models.CharField(max_length=100, verbose_name='نام لاتین')),
                ('bomi', models.TextField(verbose_name='بومی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compounds', models.TextField(verbose_name='ترکیبات')),
                ('amount_of_compounds', models.TextField(verbose_name='مقدار ترکیبات')),
                ('indications', models.TextField(verbose_name='موارد مصرف')),
                ('prohibited_usage', models.TextField(verbose_name='موارد منع مصرف')),
                ('complications', models.TextField(verbose_name='عوارض')),
                ('pregnancy', models.TextField(verbose_name='بارداری')),
                ('method_of_drug_production', models.TextField(verbose_name='روش تولید دارو')),
                ('how_to_use', models.TextField(verbose_name='طریقه مصرف')),
                ('treatment_duration', models.TextField(verbose_name='طول درمان')),
                ('pharmaceutical_supplements', models.TextField(verbose_name='مکمل های دارویی')),
                ('the_nature_of_the_drug', models.CharField(max_length=50, verbose_name='طبیعت دارو')),
                ('drug_manufacturing_company', models.TextField(verbose_name='شرکت تولید کننده دارو')),
            ],
            options={
                'verbose_name': 'دانشنامه داروهای ترکیبی',
                'verbose_name_plural': 'دانشنامه داروهای ترکیبی',
            },
        ),
        migrations.CreateModel(
            name='EncyclopediaOfDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'Report'), (2, 'Failed'), (3, 'Accept')], default=0)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('another_name', models.CharField(max_length=50, unique=True, verbose_name='نام دیگر')),
                ('latin_name', models.CharField(max_length=50, unique=True, verbose_name='نام لاتین')),
                ('classification', models.CharField(max_length=50, verbose_name='دسته بندی')),
                ('native', models.CharField(max_length=50, verbose_name='زیست بوم')),
                ('history', models.CharField(max_length=50, verbose_name='تاریخچه')),
                ('the_structure_of_the_disease', models.CharField(max_length=50, verbose_name='ساختار بیماری')),
                ('cause_of_illness', models.CharField(max_length=50, verbose_name='علت بیماری')),
                ('disease_factors', models.CharField(max_length=50, verbose_name='عوامل بیماری')),
                ('course_of_illness', models.CharField(max_length=50, verbose_name='دوره بیماری')),
                ('treatment_methods', models.CharField(max_length=50, verbose_name='روش های درمان')),
                ('treatment_duration', models.CharField(max_length=50, verbose_name='درمان مدت')),
                ('coping_method', models.CharField(max_length=50, verbose_name='روش مقابله')),
                ('disease_prevention', models.CharField(max_length=50, verbose_name='پیشگیری از بیماری')),
                ('cases_of_exacerbation_of_the_disease', models.CharField(max_length=50, verbose_name='موارد تشدید بیماری')),
                ('pregnancy', models.TextField(verbose_name='بارداری')),
                ('hereditary_history', models.TextField(verbose_name='سابقه وراثتی')),
                ('type_of_disease', models.TextField(verbose_name='نوع بیماری')),
                ('phase_description_from_start_to_finish', models.TextField(verbose_name='توضیجات فاز شروع تا پایان بیماری')),
            ],
            options={
                'verbose_name': 'دایره المعارف بیماری ',
                'verbose_name_plural': 'دایره المعارف بیماری ها',
            },
        ),
        migrations.CreateModel(
            name='HerbalEncyclopedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'Report'), (2, 'Failed'), (3, 'Accept')], default=0)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام')),
                ('another_name', models.CharField(max_length=50, unique=True, verbose_name='نام دیگر')),
                ('latin_name', models.CharField(max_length=54, unique=True, verbose_name='نام لاتین')),
                ('habitat', models.CharField(max_length=40, verbose_name='زیستگاه')),
                ('history', models.CharField(max_length=50, unique=True, verbose_name='تاریخه')),
                ('components', models.TextField(verbose_name='اجزاء')),
                ('compounds', models.TextField(verbose_name='ترکیبات')),
                ('pharmacology', models.TextField(verbose_name='داروشناسی')),
                ('indications', models.TextField(verbose_name='نشانه ها')),
                ('effects', models.TextField(verbose_name='اثرات')),
                ('the_nature_of_the_plant', models.TextField(verbose_name='طبیعت گیاه')),
                ('complications', models.TextField(verbose_name='عوارض')),
                ('pregnancy', models.TextField(verbose_name='بارداری')),
                ('treatment_duration', models.TextField(verbose_name='درمان مدت')),
                ('lifespan_of_the_plant', models.TextField(verbose_name='طول عمر گیاه')),
                ('prohibited_usage', models.TextField(verbose_name='استفاده ممنوع')),
                ('supplements', models.TextField(verbose_name='مکمل')),
                ('maintenance_method', models.TextField(verbose_name='نگهداری روش')),
                ('plant_structure', models.TextField(verbose_name='گیاه ساختار')),
                ('plant_type', models.TextField(verbose_name='گیاه نوع')),
                ('dosage', models.TextField(verbose_name='مقدار مصرف')),
                ('how_to_use', models.TextField(verbose_name='نحوه استفاده')),
            ],
            options={
                'verbose_name': 'دایره المعارف گیاهی',
                'verbose_name_plural': 'دایره المعارف های گیاهی',
            },
        ),
        migrations.CreateModel(
            name='NewsPaperEncyclopedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='logo/encyclopedia/new-paper')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نویسنده')),
                ('link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HerbalEncyclopediaReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herbal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.herbalencyclopedia')),
                ('refrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.articlereference')),
            ],
            options={
                'verbose_name': 'ارجاع',
                'verbose_name_plural': 'ارجاعات',
            },
        ),
        migrations.CreateModel(
            name='HerbalEncyclopediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='herbal-encycloperdia', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])], verbose_name='تصویر')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.herbalencyclopedia')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='HerbalEncyclopediaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.articleencyclopedia')),
                ('herbal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.herbalencyclopedia')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='EncyclopediaOfDiseasesReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('herbal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.encyclopediaofdiseases')),
                ('refrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.articlereference')),
            ],
            options={
                'verbose_name': 'ارجاع',
                'verbose_name_plural': 'ارجاعات',
            },
        ),
        migrations.CreateModel(
            name='EncyclopediaOfDiseasesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='encyclopedia-of-diseases', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])], verbose_name='تصاویر')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.encyclopediaofdiseases')),
            ],
        ),
        migrations.CreateModel(
            name='EncyclopediaOfDiseasesArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.articleencyclopedia')),
                ('encyclopedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.encyclopediaofdiseases')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='EncyclopediaCombinedDrugsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='EncyclopediaCombinedDrugs/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg', 'jpeg'])])),
                ('encyclopedia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.encyclopediacombineddrugs')),
            ],
            options={
                'verbose_name': 'تصاویر داروهای ترکیبی',
                'verbose_name_plural': 'تصاویر داروهای ترکیبی',
            },
        ),
        migrations.CreateModel(
            name='EncyclopediaCombinedDrugsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.articleencyclopedia')),
                ('encyclopedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.encyclopediacombineddrugs')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='EncyclopediaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.articleencyclopedia', verbose_name='مقاله')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.articlereference', verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'مرجع مقاله',
                'verbose_name_plural': 'مراجع مقاله',
            },
        ),
        migrations.CreateModel(
            name='ArticleEncyclopediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='عنوان')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.articleencyclopediacategory', verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AddField(
            model_name='articleencyclopedia',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.articleencyclopediacategory', verbose_name='دسته بندی'),
        ),
    ]
