# Generated by Django 5.0 on 2025-03-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleencyclopedia',
            name='author',
            field=models.CharField(max_length=100, verbose_name='نویسنده'),
        ),
    ]
