# Generated by Django 5.0 on 2025-03-01 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_alter_articleencyclopedia_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='encyclopediaofdiseases',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
