# Generated by Django 4.2.3 on 2023-09-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_encyclopaediaprescriptiontherapy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encyclopediacombineddrugsimage',
            options={'verbose_name': 'تصاویر داروهای ترکیبی', 'verbose_name_plural': 'تصاویر داروهای ترکیبی'},
        ),
    ]
