# Generated by Django 4.2.3 on 2023-09-14 11:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_alter_encyclopediacombineddrugsimage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncyclopediaOfDiseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('another_name', models.CharField(max_length=50, verbose_name='نام دیگر')),
                ('latin_name', models.CharField(max_length=50, verbose_name='نام لاتین')),
                ('classification', models.CharField(max_length=50, verbose_name='دسته بندی')),
                ('native', models.CharField(max_length=50, verbose_name='زیست بوم')),
                ('history', models.CharField(max_length=50, verbose_name='تاریخچه')),
                ('the_structure_of_the_disease', models.CharField(max_length=50, verbose_name='ساختار بیماری')),
                ('cause_of_illness', models.CharField(max_length=50, verbose_name='علت بیماری')),
                ('disease_factors', models.CharField(max_length=50, verbose_name='عوامل بیماری')),
                ('course_of_illness', models.CharField(max_length=50, verbose_name='دوره بیماری')),
                ('treatment_methods', models.CharField(max_length=50, verbose_name='روش های درمان')),
                ('treatment_duration', models.CharField(max_length=50, verbose_name='درمان مدت')),
                ('coping_method', models.CharField(max_length=50, verbose_name='روش مقابله')),
                ('disease_prevention', models.CharField(max_length=50, verbose_name='پیشگیری از بیماری')),
                ('cases_of_exacerbation_of_the_disease', models.CharField(max_length=50, verbose_name='موارد تشدید بیماری')),
                ('pregnancy', models.TextField(verbose_name='بارداری')),
                ('hereditary_history', models.TextField(verbose_name='سابقه وراثتی')),
                ('type_of_disease', models.TextField(verbose_name='نوع بیماری')),
                ('phase_description_from_start_to_finish', models.TextField(verbose_name='توضیجات فاز شروع تا پایان بیماری')),
                ('articles', models.TextField(verbose_name='مقالات')),
                ('reference', models.TextField(verbose_name='مراجع')),
            ],
        ),
        migrations.CreateModel(
            name='HerbalEncyclopedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('another_name', models.CharField(max_length=50, verbose_name='نام دیگر')),
                ('latin_name', models.CharField(max_length=54, verbose_name='نام لاتین')),
                ('habitat', models.CharField(max_length=40, verbose_name='زیستگاه')),
                ('history', models.CharField(max_length=50, verbose_name='تاریخه')),
                ('components', models.TextField(verbose_name='اجزاء')),
                ('compounds', models.TextField(verbose_name='ترکیبات')),
                ('pharmacology', models.TextField(verbose_name='داروشناسی')),
                ('indications', models.TextField(verbose_name='نشانه ها')),
                ('effects', models.TextField(verbose_name='اثرات')),
                ('the_nature_of_the_plant', models.TextField(verbose_name='طبیعت گیاه')),
                ('complications', models.TextField(verbose_name='عوارض')),
                ('pregnancy', models.TextField(verbose_name='بارداری')),
                ('treatment_duration', models.TextField(verbose_name='درمان مدت')),
                ('lifespan_of_the_plant', models.TextField(verbose_name='طول عمر گیاه')),
                ('prohibited_usage', models.TextField(verbose_name='استفاده ممنوع')),
                ('supplements', models.TextField(verbose_name='مکمل')),
                ('maintenance_method', models.TextField(verbose_name='نگهداری روش')),
                ('plant_structure', models.TextField(verbose_name='گیاه ساختار')),
                ('plant_type', models.TextField(verbose_name='گیاه نوع')),
                ('dosage', models.TextField(verbose_name='مقدار مصرف')),
                ('how_to_use', models.TextField(verbose_name='نحوه استفاده')),
                ('articles', models.TextField(verbose_name='مقالات')),
                ('reference', models.TextField(verbose_name='ارجاع')),
            ],
        ),
        migrations.CreateModel(
            name='HerbalEncyclopediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='herbal-encycloperdia', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])], verbose_name='تصویر')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.herbalencyclopedia')),
            ],
        ),
        migrations.CreateModel(
            name='EncyclopediaOfDiseasesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='encyclopedia-of-diseases', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'svg'])], verbose_name='تصاویر')),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.encyclopediaofdiseases')),
            ],
        ),
    ]
