# Generated by Django 5.0 on 2025-03-01 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_encyclopediaofdiseases_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encyclopediaofdiseasesarticle',
            options={'verbose_name': 'مقاله بیماری', 'verbose_name_plural': 'مقالات بیماری'},
        ),
        migrations.AddField(
            model_name='herbalencyclopedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
