# Generated by Django 4.2.3 on 2023-10-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0004_encyclopediaofdiseases_herbalencyclopedia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encyclopediaofdiseases',
            options={'verbose_name': 'دایره المعارف بیماری ', 'verbose_name_plural': 'دایره المعارف بیماری ها'},
        ),
        migrations.AlterModelOptions(
            name='herbalencyclopedia',
            options={'verbose_name': 'دایره المعارف گیاهی', 'verbose_name_plural': 'دایره المعارف های گیاهی'},
        ),
        migrations.AlterField(
            model_name='articleencyclopediacategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.articleencyclopediacategory', verbose_name='منبع'),
        ),
    ]
