# Generated by Django 4.2.3 on 2023-10-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0006_remove_herbalencyclopedia_reference_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herbalencyclopediaimage',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterModelOptions(
            name='herbalencyclopediareference',
            options={'verbose_name': 'ارجاع', 'verbose_name_plural': 'ارجاعات'},
        ),
        migrations.AddField(
            model_name='encyclopaediaprescriptiontherapy',
            name='state',
            field=models.IntegerField(choices=[(0, 'Suspend'), (1, 'Report'), (2, 'Failed'), (3, 'Accept')], default=0),
        ),
        migrations.AddField(
            model_name='encyclopediacombineddrugs',
            name='state',
            field=models.IntegerField(choices=[(0, 'Suspend'), (1, 'Report'), (2, 'Failed'), (3, 'Accept')], default=0),
        ),
        migrations.AddField(
            model_name='encyclopediaofdiseases',
            name='state',
            field=models.IntegerField(choices=[(0, 'Suspend'), (1, 'Report'), (2, 'Failed'), (3, 'Accept')], default=0),
        ),
        migrations.AddField(
            model_name='herbalencyclopedia',
            name='state',
            field=models.IntegerField(choices=[(0, 'Suspend'), (1, 'Report'), (2, 'Failed'), (3, 'Accept')], default=0),
        ),
    ]
