# Generated by Django 4.2.3 on 2023-10-20 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0008_remove_encyclopediaofdiseases_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncyclopediaCombinedDrugsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.articleencyclopedia')),
                ('encyclopedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.encyclopediacombineddrugs')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
