# Generated by Django 4.2.3 on 2023-10-20 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0009_encyclopediacombineddrugsarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encyclopediacombineddrugs',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='herbalencyclopedia',
            name='articles',
        ),
        migrations.CreateModel(
            name='HerbalEncyclopediaArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.articleencyclopedia')),
                ('herbal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.herbalencyclopedia')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='EncyclopediaOfDiseasesArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.articleencyclopedia')),
                ('encyclopedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encyclopedia.encyclopediaofdiseases')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
