# Generated by Django 4.2.3 on 2023-10-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0010_remove_encyclopediacombineddrugs_articles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encyclopediaofdiseases',
            name='articles',
        ),
    ]
