# Generated by Django 4.2.3 on 2023-11-16 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0011_remove_encyclopediaofdiseases_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPaperEncyclopedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='logo/encyclopedia/new-paper')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نویسنده')),
                ('link', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='articleencyclopedia',
            name='author',
            field=models.CharField(default=1, max_length=100, unique=True, verbose_name='نویسنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articleencyclopedia',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='articleencyclopediacategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='articleencyclopediacategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.articleencyclopediacategory', unique=True, verbose_name='منبع'),
        ),
        migrations.AlterField(
            model_name='articlereference',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='encyclopaediaprescriptiontherapy',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='encyclopaediaprescriptiontherapy',
            name='prescription_compounds',
            field=models.TextField(unique=True, verbose_name='ترکیبات نسخه'),
        ),
        migrations.AlterField(
            model_name='encyclopediacombineddrugs',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='encyclopediaofdiseases',
            name='another_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام دیگر'),
        ),
        migrations.AlterField(
            model_name='encyclopediaofdiseases',
            name='latin_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام لاتین'),
        ),
        migrations.AlterField(
            model_name='encyclopediaofdiseases',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='herbalencyclopedia',
            name='another_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام دیگر'),
        ),
        migrations.AlterField(
            model_name='herbalencyclopedia',
            name='history',
            field=models.CharField(max_length=50, unique=True, verbose_name='تاریخه'),
        ),
        migrations.AlterField(
            model_name='herbalencyclopedia',
            name='latin_name',
            field=models.CharField(max_length=54, unique=True, verbose_name='نام لاتین'),
        ),
        migrations.AlterField(
            model_name='herbalencyclopedia',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام'),
        ),
    ]
