# Generated by Django 4.2 on 2024-01-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0012_newspaperencyclopedia_articleencyclopedia_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleencyclopediacategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='encyclopedia.articleencyclopediacategory', verbose_name='منبع'),
        ),
    ]
