# Generated by Django 4.2 on 2024-01-10 11:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0014_alter_articleencyclopedia_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleencyclopedia',
            name='image',
            field=models.FileField(default=1, upload_to='article-encyclopedia/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'svg', 'jpeg'])], verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
