# Generated by Django 4.2 on 2024-01-10 11:34

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0015_articleencyclopedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleencyclopedia',
            name='created_at',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
    ]
