# Generated by Django 4.2.3 on 2024-01-17 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'In Process'), (2, 'Passed'), (3, 'Failed')], default=0)),
                ('message', models.TextField(verbose_name='پیام')),
                ('plaintiff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintiff_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر خواهان')),
                ('reported_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر گزارش شده')),
            ],
            options={
                'verbose_name': 'گزارش کاربر',
                'verbose_name_plural': 'گزارش\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='ShopReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'In Process'), (2, 'Passed'), (3, 'Failed')], default=0)),
                ('message', models.TextField(verbose_name='پیام')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='فروشگاه')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش فروشگاه',
                'verbose_name_plural': 'گزارش\u200cهای فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='DoctorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'In Process'), (2, 'Passed'), (3, 'Failed')], default=0)),
                ('message', models.TextField(verbose_name='پیام')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor', verbose_name='دکتر')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گزارش دکتر',
                'verbose_name_plural': 'گزارش\u200cهای دکتر',
            },
        ),
    ]
