# Generated by Django 4.2.3 on 2023-10-19 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_dockterbranch_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_alter_shop_options_alter_shopimage_options_and_more'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorreport',
            options={'verbose_name': 'گزارش دکتر', 'verbose_name_plural': 'گزارش\u200cهای دکتر'},
        ),
        migrations.AlterModelOptions(
            name='shopreport',
            options={'verbose_name': 'گزارش فروشگاه', 'verbose_name_plural': 'گزارش\u200cهای فروشگاه'},
        ),
        migrations.AlterModelOptions(
            name='userreport',
            options={'verbose_name': 'گزارش کاربر', 'verbose_name_plural': 'گزارش\u200cهای کاربران'},
        ),
        migrations.AlterField(
            model_name='doctorreport',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor', verbose_name='دکتر'),
        ),
        migrations.AlterField(
            model_name='doctorreport',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='doctorreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='shopreport',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='shopreport',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shopreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='message',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='plaintiff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plaintiff_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر خواهان'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reported_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر گزارش شده'),
        ),
    ]
