# Generated by Django 5.0 on 2025-02-27 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
        ('shop', '0007_shopproduct_how_to_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopreport',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_report', to='shop.shop', verbose_name='فروشگاه'),
        ),
    ]
