# Generated by Django 4.2.3 on 2023-10-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_doctorreport_options_alter_shopreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorreport',
            name='state',
            field=models.IntegerField(choices=[(0, 'Suspend'), (1, 'In Process'), (2, 'Passed'), (3, 'Failed')], default=0),
        ),
        migrations.AddField(
            model_name='shopreport',
            name='state',
            field=models.IntegerField(choices=[(0, 'Suspend'), (1, 'In Process'), (2, 'Passed'), (3, 'Failed')], default=0),
        ),
        migrations.AddField(
            model_name='userreport',
            name='state',
            field=models.IntegerField(choices=[(0, 'Suspend'), (1, 'In Process'), (2, 'Passed'), (3, 'Failed')], default=0),
        ),
    ]
