# Generated by Django 5.0 on 2025-05-20 12:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_visit', '0001_initial'),
        ('sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='مبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('transaction_type', models.IntegerField(choices=[(0, 'در انتظار'), (1, 'درخواست شده'), (2, 'تأیید شده'), (3, 'ناموفق'), (4, 'اتمام زمان')], default=0, verbose_name='وضعیت تراکنش')),
                ('card', models.CharField(blank=True, max_length=33, null=True, verbose_name='شماره کارت')),
                ('card_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='هش کارت')),
                ('ref_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='کد پیگیری')),
                ('authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='Authority')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش پزشک',
                'verbose_name_plural': 'تراکنش\u200cهای پزشکان',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_type', models.IntegerField(choices=[(1, 'پست'), (2, 'اسنپ')], default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ')),
                ('transaction_type', models.CharField(choices=[('deposit', 'واریز'), ('withdrawal', 'برداشت')], max_length=10, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق'), ('pending', 'در انتظار'), ('cancel', 'لغو شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تراکنش')),
                ('authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='Authority')),
                ('message', models.TextField(blank=True, null=True, verbose_name='پیام')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('lat', models.TextField(blank=True, null=True, verbose_name='عرض جغرافیایی')),
                ('lng', models.TextField(blank=True, null=True, verbose_name='طول جغرافیایی')),
                ('code_posti', models.CharField(default='', max_length=40, verbose_name='کد پستی')),
                ('card', models.CharField(blank=True, max_length=33, null=True, verbose_name='شماره کارت')),
                ('card_hash', models.CharField(blank=True, max_length=128, null=True, verbose_name='هش کارت')),
                ('ref_id', models.CharField(blank=True, max_length=32, null=True, verbose_name='کد پیگیری')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_transaction', to='sale.salebasket', verbose_name='سبد خرید')),
                ('doctor_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='doctor_visit.doctorvisit', verbose_name='ویزیت پزشک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_url', models.URLField(blank=True, null=True, verbose_name='آدرس پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.salebasket', verbose_name='سبد خرید')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction', verbose_name='تراکنش مرتبط')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
    ]
