# Generated by Django 5.0 on 2025-05-17 06:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_visit', '0002_initial'),
        ('sale', '0003_remove_salebasket_shop'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctortransaction',
            options={'verbose_name': 'تراکنش پزشک', 'verbose_name_plural': 'تراکنش\u200cهای پزشکان'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'پرداخت', 'verbose_name_plural': 'پرداخت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش\u200cها'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='courier_type',
            field=models.IntegerField(choices=[(1, 'پست'), (2, 'اسنپ')], default=1),
        ),
        migrations.AlterField(
            model_name='doctortransaction',
            name='amount',
            field=models.IntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='doctortransaction',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Authority'),
        ),
        migrations.AlterField(
            model_name='doctortransaction',
            name='card',
            field=models.CharField(blank=True, max_length=33, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='doctortransaction',
            name='card_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='هش کارت'),
        ),
        migrations.AlterField(
            model_name='doctortransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='doctortransaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='doctortransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(0, 'در انتظار'), (1, 'درخواست شده'), (2, 'تأیید شده'), (3, 'ناموفق'), (4, 'اتمام زمان')], default=0, verbose_name='وضعیت تراکنش'),
        ),
        migrations.AlterField(
            model_name='doctortransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.salebasket', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction', verbose_name='تراکنش مرتبط'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Authority'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.CharField(blank=True, max_length=33, null=True, verbose_name='شماره کارت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='هش کارت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_transaction', to='sale.salebasket', verbose_name='سبد خرید'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='code_posti',
            field=models.CharField(default='', max_length=40, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='doctor_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='doctor_visit.doctorvisit', verbose_name='ویزیت پزشک'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lat',
            field=models.TextField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='lng',
            field=models.TextField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'موفق'), ('failed', 'ناموفق'), ('pending', 'در انتظار'), ('cancel', 'لغو شده')], default='pending', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'واریز'), ('withdrawal', 'برداشت')], max_length=10, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
