# Generated by Django 4.2.3 on 2025-02-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='code_posti',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lng',
            field=models.TextField(blank=True, null=True),
        ),
    ]
