# Generated by Django 4.2.3 on 2025-02-11 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_salebasket_price_alter_salebasket_session_key'),
        ('transaction', '0003_transaction_address_transaction_code_posti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_transaction', to='sale.salebasket'),
        ),
    ]
