# Generated by Django 4.2.3 on 2025-02-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transaction_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.CharField(blank=True, max_length=33, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='card_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
