# Generated by Django 5.0 on 2025-03-04 13:10

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='نام')),
                ('trade_id', models.CharField(max_length=19, verbose_name='شناسه تجاری')),
                ('state', models.IntegerField(choices=[(0, 'انتظار'), (1, 'فعال'), (2, 'غیر فعال'), (3, 'گزارش شده'), (4, 'نیاز به تکمیل پروفایل')], default=0, verbose_name='وضعیت')),
                ('shop_home', models.TextField(verbose_name='آدرس فروشگاه')),
                ('image', models.FileField(upload_to='shop/image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر')),
                ('national_code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='کدملی')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('catalog', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='کاتالوگ')),
                ('rate_state', models.IntegerField(choices=[(0, 'سیاه'), (1, 'سفید'), (2, 'برنز'), (3, 'طلایی')], default=1, verbose_name='وضعیت امتیاز')),
                ('price', models.IntegerField(default=0, verbose_name='واحد قیمت بر حسب واحد')),
                ('location_lat', models.CharField(default='35.7475', max_length=12)),
                ('location_lng', models.CharField(default='51.2358', max_length=12)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='CertificateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.FileField(upload_to='shop/certificate/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر مجوز')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'تصویر فروشگاه',
                'verbose_name_plural': 'تصاویر فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='shop/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر  ')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'تصویر فروشگاه',
                'verbose_name_plural': 'تصاویر فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='ShopPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, unique=True, verbose_name='تلفن')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'تلفن فروشگاه',
                'verbose_name_plural': 'تلفن\u200cهای فروشگاه',
            },
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('capacity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ظرفیت')),
                ('inventory_state', models.IntegerField(choices=[(0, 'در دسترس'), (1, 'در دسترس نیست')], default=1, verbose_name='وضعیت موجودی')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت')),
                ('material', models.IntegerField(choices=[(1, 'بسته بندی'), (2, 'پک'), (3, 'دانه ای'), (4, 'کیلوای'), (5, 'شیشه ای')], default=1, verbose_name='جنس کالا')),
                ('how_to_use', models.CharField(default='نحوه مصرف', max_length=255)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='محصول')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'محصول فروشگاه',
                'verbose_name_plural': 'محصولات فروشگاه',
            },
        ),
    ]
