# Generated by Django 4.2.3 on 2024-01-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='کدملی'),
        ),
    ]
