# Generated by Django 5.0 on 2025-05-17 06:29

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productneedtoadded',
            options={'verbose_name': 'درخواست افزودن محصول', 'verbose_name_plural': 'درخواست\u200cهای افزودن محصول'},
        ),
        migrations.AlterModelOptions(
            name='shopsettlement',
            options={'verbose_name': 'تسویه\u200cحساب فروشگاه', 'verbose_name_plural': 'تسویه\u200cحساب\u200cهای فروشگاه\u200cها'},
        ),
        migrations.AlterField(
            model_name='productneedtoadded',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات محصول'),
        ),
        migrations.AlterField(
            model_name='productneedtoadded',
            name='image',
            field=models.FileField(blank=True, upload_to='shop/image/need_product/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر محصول'),
        ),
        migrations.AlterField(
            model_name='productneedtoadded',
            name='name',
            field=models.CharField(max_length=33, unique=True, verbose_name='نام محصول پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='productneedtoadded',
            name='state',
            field=models.IntegerField(choices=[(1, 'در انتظار بررسی'), (2, 'گزارش\u200cشده'), (3, 'تایید شده'), (4, 'در حال پردازش')], default=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='banner_1',
            field=models.FileField(blank=True, null=True, upload_to='shop/banner/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='بنر ۱'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='banner_2',
            field=models.FileField(blank=True, null=True, upload_to='shop/banner/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='بنر ۲'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='banner_3',
            field=models.FileField(blank=True, null=True, upload_to='shop/banner/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='بنر ۳'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='catalog',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='کاتالوگ محصولات'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='cert_1',
            field=models.FileField(blank=True, null=True, upload_to='shop/cert/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='گواهی\u200cنامه ۱'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='cert_2',
            field=models.FileField(blank=True, null=True, upload_to='shop/cert/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='گواهی\u200cنامه ۲'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='end_time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='ساعت پایان فعالیت'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='shop/image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location_lat',
            field=models.CharField(default='35.7475', max_length=12, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='location_lng',
            field=models.CharField(default='51.2358', max_length=12, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='نام فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rate_state',
            field=models.IntegerField(choices=[(0, 'سیاه'), (1, 'سفید'), (2, 'برنزی'), (3, 'طلایی')], default=1, verbose_name='وضعیت امتیازدهی'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_phones',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='start_time',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='ساعت شروع فعالیت'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.IntegerField(choices=[(0, 'در انتظار تایید'), (1, 'فعال'), (2, 'غیرفعال'), (3, 'گزارش\u200cشده'), (4, 'نیازمند تکمیل اطلاعات')], default=0, verbose_name='وضعیت فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='telegram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='whats_app',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='واتساپ'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ظرفیت موجود'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='how_to_use',
            field=models.CharField(default='نحوه مصرف', max_length=255, verbose_name='راهنمای مصرف'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inventory_state',
            field=models.IntegerField(choices=[(0, 'موجود'), (1, 'ناموجود')], default=1, verbose_name='وضعیت موجودی'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='material',
            field=models.IntegerField(choices=[(1, 'بسته\u200cبندی'), (2, 'پک'), (3, 'دانه\u200cای'), (4, 'کیلویی'), (5, 'شیشه\u200cای')], default=1, verbose_name='نوع بسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت کالا'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='shopsettlement',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='shopsettlement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='shopsettlement',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='settlements/receipts/', verbose_name='تصویر رسید پرداخت'),
        ),
        migrations.AlterField(
            model_name='shopsettlement',
            name='status',
            field=models.IntegerField(choices=[(0, 'در انتظار بررسی'), (1, 'تایید شده'), (2, 'رد شده'), (3, 'پرداخت شده')], default=0, verbose_name='وضعیت تسویه'),
        ),
        migrations.AlterField(
            model_name='shopsettlement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
    ]
