# Generated by Django 5.0 on 2025-03-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_productneedtoadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='productneedtoadded',
            name='state',
            field=models.IntegerField(choices=[(1, 'Suspend'), (2, 'Report'), (3, 'Accept'), (4, 'In Progres')], default=1),
        ),
    ]
