# Generated by Django 4.2.3 on 2023-10-19 16:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_shop_rate_state_shop_trade_id_shopproduct_shopphone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'فروشگاه', 'verbose_name_plural': 'فروشگاه\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='shopimage',
            options={'verbose_name': 'تصویر فروشگاه', 'verbose_name_plural': 'تصاویر فروشگاه'},
        ),
        migrations.AlterModelOptions(
            name='shopphone',
            options={'verbose_name': 'تلفن فروشگاه', 'verbose_name_plural': 'تلفن\u200cهای فروشگاه'},
        ),
        migrations.AlterModelOptions(
            name='shopproduct',
            options={'verbose_name': 'محصول فروشگاه', 'verbose_name_plural': 'محصولات فروشگاه'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='certificate_image',
            field=models.FileField(upload_to='shop/certificate/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر گواهی'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.FileField(upload_to='shop/image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='mobile',
            field=models.CharField(max_length=15, verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=40, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rate_state',
            field=models.IntegerField(choices=[(0, 'Black'), (1, 'White'), (2, 'Bronze'), (3, 'Gold')], default=1, verbose_name='وضعیت امتیاز'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_home',
            field=models.CharField(max_length=15, verbose_name='آدرس فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'De Active'), (3, 'Reported'), (4, 'Need To Complete')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='trade_id',
            field=models.CharField(max_length=19, verbose_name='شناسه تجاری'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='certificate_image',
            field=models.FileField(upload_to='shop/certificate/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر گواهی'),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shopphone',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='shopphone',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inventory_state',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Not Available')], default=1, verbose_name='وضعیت موجودی'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='فروشگاه'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
