# Generated by Django 4.2.3 on 2024-01-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='material',
            field=models.IntegerField(choices=[(1, 'بسته بندی'), (2, 'پک'), (3, 'دانه ای'), (4, 'کیلوای'), (5, 'شیشه ای')], default=1, verbose_name='جنس کالا'),
        ),
    ]
