# Generated by Django 4.2.3 on 2023-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_options_alter_shopimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=40, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='shopphone',
            name='phone',
            field=models.CharField(max_length=13, unique=True, verbose_name='تلفن'),
        ),
    ]
