# Generated by Django 5.0 on 2024-10-21 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopproduct_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=0, verbose_name='واحد قیمت بر حسب واحد'),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='image',
            field=models.FileField(null=True, upload_to='shop/image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
