# Generated by Django 4.2 on 2024-01-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_name_alter_shopphone_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='certificate_image',
        ),
    ]
