# Generated by Django 5.0 on 2025-03-21 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shopsettlement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopimage',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shopphone',
            name='shop',
        ),
        migrations.AddField(
            model_name='shop',
            name='banner_1',
            field=models.FileField(blank=True, null=True, upload_to='shop/banner/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='shop',
            name='banner_2',
            field=models.FileField(blank=True, null=True, upload_to='shop/banner/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='shop',
            name='banner_3',
            field=models.FileField(blank=True, null=True, upload_to='shop/banner/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='shop',
            name='cert_1',
            field=models.FileField(blank=True, null=True, upload_to='shop/cert/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='shop',
            name='cert_2',
            field=models.FileField(blank=True, null=True, upload_to='shop/cert/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_phones',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='shop/image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر'),
        ),
        migrations.DeleteModel(
            name='CertificateImage',
        ),
        migrations.DeleteModel(
            name='ShopImage',
        ),
        migrations.DeleteModel(
            name='ShopPhone',
        ),
    ]
