# Generated by Django 5.0 on 2024-10-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_price_shopproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='image',
        ),
    ]
