# Generated by Django 4.2.3 on 2024-12-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_shopproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='location_lat',
            field=models.CharField(default='35.7475', max_length=12),
        ),
        migrations.AddField(
            model_name='shop',
            name='location_lng',
            field=models.CharField(default='51.2358', max_length=12),
        ),
    ]
