# Generated by Django 4.2 on 2024-01-05 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_shop_certificate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopimage',
            name='certificate_image',
        ),
        migrations.AddField(
            model_name='shopimage',
            name='image',
            field=models.FileField(default=1, upload_to='shop/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر  '),
            preserve_default=False,
        ),
    ]
