# Generated by Django 4.2 on 2024-01-05 12:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_shopimage_certificate_image_shopimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_image', models.FileField(upload_to='shop/certificate/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر مجوز')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop', verbose_name='فروشگاه')),
            ],
            options={
                'verbose_name': 'تصویر فروشگاه',
                'verbose_name_plural': 'تصاویر فروشگاه',
            },
        ),
    ]
