# Generated by Django 4.2.3 on 2024-12-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_shop_location_lat_shop_location_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='how_to_use',
            field=models.CharField(default='نحوه مصرف', max_length=255),
        ),
    ]
