# Generated by Django 4.2 on 2024-01-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_certificateimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='rate_state',
            field=models.IntegerField(choices=[(0, 'سیاه'), (1, 'سفید'), (2, 'برنز'), (3, 'طلایی')], default=1, verbose_name='وضعیت امتیاز'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.IntegerField(choices=[(0, 'انتظار'), (1, 'فعال'), (2, 'غیر فعال'), (3, 'گزارش شده'), (4, 'نیاز به تکمیل پروفایل')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='inventory_state',
            field=models.IntegerField(choices=[(0, 'در دسترس'), (1, 'در دسترس نیست')], default=1, verbose_name='وضعیت موجودی'),
        ),
    ]
