# Generated by Django 5.0 on 2025-02-27 13:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shopproduct_how_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='catalog',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='معرفی محصول'),
        ),
    ]
