# Generated by Django 4.2 on 2024-01-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_shop_rate_state_alter_shop_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_home',
            field=models.TextField(verbose_name='آدرس فروشگاه'),
        ),
    ]
