# Generated by Django 5.0 on 2025-02-27 13:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shop_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='catalog',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='کاتالوگ'),
        ),
    ]
