# Generated by Django 4.2 on 2024-01-10 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_shop_shop_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='mobile',
        ),
    ]
