# Generated by Django 5.0 on 2025-05-17 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف\u200cهای پول'},
        ),
    ]
