# Generated by Django 4.2.3 on 2023-10-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionalMedicineDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام بیماری')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('causes', models.TextField(verbose_name='علل بیماری')),
                ('symptoms', models.TextField(verbose_name='علائم بیماری')),
                ('treatments', models.TextField(verbose_name='درمان\u200cهای طب سنتی')),
                ('prevention', models.TextField(verbose_name='پیشگیری از بیماری')),
            ],
            options={
                'verbose_name': 'بیماری طب سنتی',
                'verbose_name_plural': 'بیماری\u200cهای طب سنتی',
            },
        ),
    ]
