# Generated by Django 4.2.3 on 2023-10-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sickness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traditionalmedicinedisease',
            options={'verbose_name': 'بیماری', 'verbose_name_plural': 'بیماری\u200cها'},
        ),
    ]
