# Generated by Django 4.2.3 on 2023-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sickness', '0002_alter_traditionalmedicinedisease_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traditionalmedicinedisease',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='نام بیماری'),
        ),
    ]
