# Generated by Django 4.2.3 on 2023-10-19 16:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0002_shop_rate_state_shop_trade_id_shopproduct_shopphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('address', models.TextField()),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'In Pay'), (2, 'Pay Failed'), (3, 'Pay Success'), (4, 'In Shop Compilation'), (5, 'Sending'), (6, 'Send Back'), (7, 'In Post Office'), (8, 'Done And Finish'), (9, 'Cancelled')], default=0)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.transaction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleBasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('basket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.salebasket')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopproduct')),
            ],
        ),
    ]
