# Generated by Django 5.0 on 2025-05-17 05:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=200, null=True, verbose_name='کلید جلسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('price', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'In Pay'), (2, 'Pay Failed'), (3, 'Pay Success'), (4, 'In Shop Compilation'), (5, 'Sending'), (6, 'Send Back'), (7, 'In Post Office'), (8, 'Done And Finish'), (9, 'Cancelled'), (10, 'Shop Cancel')], default=0, verbose_name='وضعیت')),
                ('discount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تخفیف')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='زمان تحویل')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبد\u200cهای خرید',
            },
        ),
        migrations.CreateModel(
            name='SaleBasketProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('unit', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد')),
                ('rate', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='ریت')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='نظر')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'محصول سبد خرید',
                'verbose_name_plural': 'محصولات سبد خرید',
            },
        ),
    ]
