# Generated by Django 5.0 on 2024-10-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebasket',
            name='session_key',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
