# Generated by Django 5.0 on 2024-11-03 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_salebasket_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebasket',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='salebasket',
            name='session_key',
            field=models.CharField(max_length=200, null=True, verbose_name='کلید جلسه'),
        ),
    ]
