# Generated by Django 4.2.3 on 2023-11-16 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_salebasket_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebasket',
            name='price',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
    ]
