# Generated by Django 5.0 on 2025-03-21 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salebasket',
            name='state',
            field=models.IntegerField(choices=[(0, 'Suspend'), (1, 'In Pay'), (2, 'Pay Failed'), (3, 'Pay Success'), (4, 'In Shop Compilation'), (5, 'Sending'), (6, 'Send Back'), (7, 'In Post Office'), (8, 'Done And Finish'), (9, 'Cancelled'), (10, 'Shop Cancel')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='salebasket',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.transaction', verbose_name='تراکنش'),
        ),
    ]
