# Generated by Django 5.0 on 2025-05-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebasket',
            name='shop',
        ),
    ]
