# Generated by Django 5.0 on 2025-03-23 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_salebasket_state_alter_salebasket_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebasketproduct',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نظر'),
        ),
        migrations.AddField(
            model_name='salebasketproduct',
            name='rate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='ریت'),
        ),
        migrations.AddField(
            model_name='salebasketproduct',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
