# Generated by Django 4.2.3 on 2025-02-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_salebasket_price_alter_salebasket_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='salebasket',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='زمان تحویل'),
        ),
    ]
