# Generated by Django 5.0 on 2025-03-04 13:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('therapy', models.TextField(verbose_name='دارو و درمان')),
            ],
            options={
                'verbose_name': 'نسخه بیمار',
                'verbose_name_plural': 'نسخه های بیمار',
            },
        ),
        migrations.CreateModel(
            name='DoctorVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Request'), (1, 'Accept'), (2, 'Failed'), (3, 'End'), (4, 'Report')], default=0, verbose_name='وضعیت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('user_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز کاربر')),
                ('doctor_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز پزشک')),
                ('time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='زمان')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='نظر')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'ویزیت دکتر',
                'verbose_name_plural': 'ویزیت\u200cهای دکتر',
            },
        ),
    ]
