# Generated by Django 4.2.3 on 2023-10-19 17:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_dockterbranch_options_and_more'),
        ('doctor_visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorvisit',
            options={'verbose_name': 'ویزیت دکتر', 'verbose_name_plural': 'ویزیت\u200cهای دکتر'},
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='comment',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='پزشک'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='doctor_rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز پزشک'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='end_time',
            field=models.DateTimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientprofile', verbose_name='بیمار'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='start_time',
            field=models.DateTimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='state',
            field=models.IntegerField(choices=[(0, 'Request'), (1, 'Accept'), (2, 'Failed'), (3, 'End'), (4, 'Report')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.AlterField(
            model_name='doctorvisit',
            name='user_rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز کاربر'),
        ),
    ]
