# Generated by Django 5.0 on 2025-05-17 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_visit', '0001_initial'),
        ('sickness', '0001_initial'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorvisit',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transaction.doctortransaction'),
        ),
        migrations.AddField(
            model_name='doctorvisit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='بیمار'),
        ),
        migrations.AddField(
            model_name='doctorvisitchat',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_visit.doctorvisit'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_visit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor_visit.doctorvisit'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='traditional_medicine_disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sickness.traditionalmedicinedisease', verbose_name='بیمار'),
        ),
    ]
