# Generated by Django 5.0 on 2025-03-05 11:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_visit', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVisitChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_doctor', models.BooleanField(default=True)),
                ('content', models.TextField()),
                ('media', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['.png', '.jpeg', '.jpg', '.mp3'])])),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor_visit.doctorvisit')),
            ],
        ),
    ]
