# Generated by Django 5.0 on 2025-03-05 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_visit', '0003_doctorvisitchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvisitchat',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['.png', '.jpeg', '.jpg', '.mp3'])]),
        ),
    ]
