# Generated by Django 5.0 on 2025-03-05 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_visit', '0004_alter_doctorvisitchat_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvisitchat',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'mp3'])]),
        ),
    ]
