# Generated by Django 5.0 on 2025-03-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_visit', '0005_alter_doctorvisitchat_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvisit',
            name='state',
            field=models.IntegerField(choices=[(0, 'Request'), (1, 'Accept'), (2, 'Failed'), (3, 'Userend'), (4, 'Doctorend'), (5, 'Report')], default=0, verbose_name='وضعیت'),
        ),
    ]
