# Generated by Django 5.0 on 2025-03-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_visit', '0006_alter_doctorvisit_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorvisitchat',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
