# Generated by Django 5.0 on 2025-04-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_visit', '0008_doctorvisitchat_created_at_doctorvisitchat_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/images/'),
        ),
    ]
