# Generated by Django 5.0 on 2025-05-17 05:16

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DockterBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33, unique=True, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'شاخه پزشکی',
                'verbose_name_plural': 'شاخه\u200cهای پزشکی',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(max_length=33, verbose_name='تاریخچه')),
            ],
            options={
                'verbose_name': 'تاریخچه',
                'verbose_name_plural': 'تاریخچه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی')),
                ('public_phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تلفن')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'Active'), (2, 'De Active'), (3, 'Reported'), (4, 'Banned')], default=0, verbose_name='وضعیت')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='doctor/certificate', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر جواز')),
                ('picture', models.FileField(blank=True, upload_to='doctor/avatar', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر پرسنلی')),
                ('description', ckeditor.fields.RichTextField(default=None, verbose_name='توضیحات')),
                ('id_active', models.BooleanField(verbose_name='وضعیت فعالیت')),
                ('register_time', models.IntegerField(default=0, verbose_name='مهلت ثبت نام')),
                ('responsiveness', models.IntegerField(choices=[(0, 'Dark'), (1, 'White'), (2, 'Silver'), (3, 'Gold')], default=1, verbose_name='نوع عملکرد')),
                ('postal_code', models.CharField(max_length=12, verbose_name='کد پستی')),
                ('shaba', models.CharField(max_length=12, verbose_name='شماره شبا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('medical_system_code', models.CharField(default='2112032', max_length=10)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام')),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True, verbose_name='whatsapp')),
                ('start_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='زمان شروع')),
                ('end_time', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='زمان پایان')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.dockterbranch', verbose_name='شاخه تحصیلی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشکان',
            },
        ),
        migrations.CreateModel(
            name='DocktorPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='شماره تلفن')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'شماره تلفن پزشک',
                'verbose_name_plural': 'شماره تلفن\u200cهای پزشک',
            },
        ),
        migrations.CreateModel(
            name='DoctorSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مبلغ درخواستی')),
                ('status', models.IntegerField(choices=[(0, 'در انتظار بررسی'), (1, 'تایید شده'), (2, 'رد شده'), (3, 'پرداخت شده')], default=0, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر وضعیت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='settlements/receipts/', verbose_name='تصویر فیش پرداختی')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه تراکنش')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='فروشگاه')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorVisitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت')),
                ('timing', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='زمان')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'Active'), (2, 'De Active')], verbose_name='وضعیت')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'قیمت و زمان ویزیت دکتر',
                'verbose_name_plural': 'قیمت و زمان ویزیت\u200cهای دکتر',
            },
        ),
        migrations.CreateModel(
            name='DoctorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='پزشک')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.history', verbose_name='تاریخچه')),
            ],
            options={
                'verbose_name': 'تاریخچه دکتر',
                'verbose_name_plural': 'تاریخچه\u200cهای دکتر',
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='پزشک')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل بیمار',
                'verbose_name_plural': 'پروفایل بیماران',
            },
        ),
    ]
