# Generated by Django 5.0 on 2025-05-15 01:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='doctor/certificate', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر جواز'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='end_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='زمان پایان'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='public_phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='start_time',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='زمان شروع'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='whatsapp'),
        ),
    ]
