# Generated by Django 5.0 on 2025-03-02 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='register_time',
            field=models.IntegerField(default=0, verbose_name='مهلت ثبت نام'),
        ),
    ]
