# Generated by Django 5.0 on 2025-04-02 04:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='مبلغ درخواستی')),
                ('status', models.IntegerField(choices=[(0, 'در انتظار بررسی'), (1, 'تایید شده'), (2, 'رد شده'), (3, 'پرداخت شده')], default=0, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر وضعیت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='settlements/receipts/', verbose_name='تصویر فیش پرداختی')),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='شناسه تراکنش')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='فروشگاه')),
            ],
        ),
    ]
