# Generated by Django 4.2.3 on 2023-10-19 17:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dockterbranch',
            options={'verbose_name': 'شاخه پزشکی', 'verbose_name_plural': 'شاخه\u200cهای پزشکی'},
        ),
        migrations.AlterModelOptions(
            name='docktorphone',
            options={'verbose_name': 'شماره تلفن پزشک', 'verbose_name_plural': 'شماره تلفن\u200cهای پزشک'},
        ),
        migrations.AlterModelOptions(
            name='doctorhistory',
            options={'verbose_name': 'تاریخچه دکتر', 'verbose_name_plural': 'تاریخچه\u200cهای دکتر'},
        ),
        migrations.AlterModelOptions(
            name='doctorvisitprice',
            options={'verbose_name': 'قیمت و زمان ویزیت دکتر', 'verbose_name_plural': 'قیمت و زمان ویزیت\u200cهای دکتر'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'تاریخچه', 'verbose_name_plural': 'تاریخچه\u200cها'},
        ),
        migrations.RemoveField(
            model_name='dockterbranch',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='dockterbranch',
            name='name',
            field=models.CharField(max_length=33, unique=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='state',
            field=models.IntegerField(choices=[(0, 'Suspend'), (1, 'Active'), (2, 'De Active'), (3, 'Reported'), (4, 'Banned')], default=0, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='doctorhistory',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='پزشک'),
        ),
        migrations.AlterField(
            model_name='doctorhistory',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.history', verbose_name='تاریخچه'),
        ),
        migrations.AlterField(
            model_name='doctorvisitprice',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='پزشک'),
        ),
        migrations.AlterField(
            model_name='doctorvisitprice',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='doctorvisitprice',
            name='state',
            field=models.IntegerField(choices=[(0, 'Suspend'), (1, 'Active'), (2, 'De Active')], verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='doctorvisitprice',
            name='timing',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='زمان'),
        ),
        migrations.AlterField(
            model_name='history',
            name='history',
            field=models.TextField(max_length=33, verbose_name='تاریخچه'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor', verbose_name='پزشک'),
        ),
    ]
