# Generated by Django 4.2.3 on 2023-10-20 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_dockterbranch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'پروفایل بیمار', 'verbose_name_plural': 'پروفایل بیماران'},
        ),
    ]
