# Generated by Django 5.0 on 2025-05-20 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام بخش')),
            ],
            options={
                'verbose_name': 'بخش تیکت',
                'verbose_name_plural': 'بخش\u200cهای تیکت',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('state', models.IntegerField(blank=True, choices=[(1, 'باز'), (2, 'در حال بررسی'), (3, 'بسته شده')], default=1, null=True, verbose_name='وضعیت')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('assigned_to_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_tickets', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به پزشک')),
                ('assigned_to_store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_tickets', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به فروشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticket.ticketsection', verbose_name='بخش')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_user', models.BooleanField(default=True, verbose_name='ارسال توسط کاربر')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن پیام')),
                ('file', models.FileField(blank=True, null=True, upload_to='ticket_files/', verbose_name='فایل پیوست')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
            },
        ),
    ]
