# Generated by Django 5.0 on 2025-04-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='state',
            new_name='status',
        ),
    ]
