# Generated by Django 5.0 on 2025-03-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_rename_status_ticket_state_ticket_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
