# Generated by Django 5.0 on 2025-05-17 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_rename_type_state_ticket_state_ticket_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='ticketsection',
            options={'verbose_name': 'بخش تیکت', 'verbose_name_plural': 'بخش\u200cهای تیکت'},
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='ticket_files/', verbose_name='فایل پیوست'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_user',
            field=models.BooleanField(default=True, verbose_name='ارسال توسط کاربر'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_message', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ticket.ticket', verbose_name='تیکت'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_tickets', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به پزشک'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_tickets', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به فروشگاه'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticket.ticketsection', verbose_name='بخش'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'باز'), (2, 'در حال بررسی'), (3, 'بسته شده')], default=1, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='ticketsection',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام بخش'),
        ),
    ]
