# Generated by Django 5.0 on 2025-04-27 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'Suspend'), (1, 'Active'), (2, 'Reported'), (3, 'De Active')], default=0)),
                ('name', models.CharField(max_length=70, verbose_name='نام')),
                ('image', models.FileField(upload_to='banner/images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])], verbose_name='تصویر')),
                ('link_url', models.TextField(verbose_name='آدرس لینک')),
                ('content', models.TextField(blank=True, verbose_name='متن')),
                ('type', models.IntegerField(choices=[(1, 'Index Top Slider'), (2, 'Index Two Slider'), (3, 'Index Middle Slider'), (4, 'Index Bottom Slider'), (5, 'Search Top Two Banner')], default=1)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
            },
        ),
    ]
