# Generated by Django 4.2 on 2024-01-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'بنر', 'verbose_name_plural': 'بنرها'},
        ),
    ]
