# Generated by Django 4.2.3 on 2024-08-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='content',
            field=models.TextField(blank=True, verbose_name='متن'),
        ),
    ]
